In [238]:
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt
 import seaborn as sns
 from sklearn.preprocessing import StandardScaler
 from sklearn.model_selection import train_test_split
 from sklearn.linear_model import LogisticRegression
 from sklearn.metrics import confusion_matrix, classification_report

In [239]:
df = pd.read_csv(r'C:\project\dataset\dataset.csv')

In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13608 entries, 0 to 13607
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            13608 non-null  int64
 1   title                         13608 non-null  object
 2   url                           13608 non-null  object
 3   is_paid                       13608 non-null  bool
 4   num_subscribers               13608 non-null  int64
 5   avg_rating                    13608 non-null  float64
 6   avg_rating_recent             13608 non-null  float64
 7   rating                        13608 non-null  float64
 8   num_reviews                   13608 non-null  int64
 9   is_wishlisted                 13608 non-null  bool
 10  num_published_lectures        13608 non-null  int64
 11  num_published_practice_tests  13608 non-null  int64
 12  created                       13608 non-null  object
 13  published_time                13608 non-null  object
 14  discount_price__amount        12205 non-null  float64
 15  discount_price__currency      12205 non-null  object
 16  discount_price__price_string  12205 non-null  object
 17  price_detail__amount          13111 non-null  float64
 18  price_detail__currency        13111 non-null  object
 19  price_detail__price_string    13111 non-null  object
dtypes: bool(2), float64(5), int64(5), object(8)
memory usage: 1.9+ MB

In [241]:
 df.dropna(inplace=True)

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12205 entries, 0 to 13392
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            12205 non-null  int64
 1   title                         12205 non-null  object
 2   url                           12205 non-null  object
 3   is_paid                       12205 non-null  bool
 4   num_subscribers               12205 non-null  int64
 5   avg_rating                    12205 non-null  float64
 6   avg_rating_recent             12205 non-null  float64
 7   rating                        12205 non-null  float64
 8   num_reviews                   12205 non-null  int64
 9   is_wishlisted                 12205 non-null  bool
 10  num_published_lectures        12205 non-null  int64
 11  num_published_practice_tests  12205 non-null  int64
 12  created                       12205 non-null  object
 13  published_time                12205 non-null  object
 14  discount_price__amount        12205 non-null  float64
 15  discount_price__currency      12205 non-null  object
 16  discount_price__price_string  12205 non-null  object
 17  price_detail__amount          12205 non-null  float64
 18  price_detail__currency        12205 non-null  object
 19  price_detail__price_string    12205 non-null  object
dtypes: bool(2), float64(5), int64(5), object(8)
memory usage: 1.8+ MB

In [243]:
# Convert all text in the 'title' column to lowercase
df['title'] = df['title'].str.lower()  
# The 'str.lower()' method is used to convert all characters in the 'title' column to lowercase. 
# This ensures consistency and removes case sensitivity in the text.

# Remove leading and trailing spaces, and replace multiple spaces with a single space
df['title'] = df['title'].str.strip().replace(r'\s+', ' ', regex=True)  
# The 'str.strip()' method removes any leading or trailing spaces from the 'title' column.
# The 'replace(r'\s+', ' ', regex=True)' part replaces any sequence of one or more spaces with a single space.

# Remove any special characters (non-alphanumeric and non-space characters) from the 'title' column
df['title'] = df['title'].str.replace(r'[^\w\s]', '', regex=True)  
# The 'str.replace(r'[^\w\s]', '', regex=True)' method removes any characters that are not word characters (letters, digits, or underscores) or spaces.
# This ensures that the 'title' column only contains alphanumeric characters and spaces, removing punctuation or other special symbols.

In [244]:
df.drop( ['id', 'avg_rating', 'url', 'created', 'num_published_lectures', 'discount_price__currency', 'discount_price__amount', 'published_time','is_paid', 'discount_price__price_string','price_detail__currency','price_detail__price_string' , 'avg_rating_recent'] , inplace=True, axis=1)

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12205 entries, 0 to 13392
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         12205 non-null  object
 1   num_subscribers               12205 non-null  int64
 2   rating                        12205 non-null  float64
 3   num_reviews                   12205 non-null  int64
 4   is_wishlisted                 12205 non-null  bool
 5   num_published_practice_tests  12205 non-null  int64
 6   price_detail__amount          12205 non-null  float64
dtypes: bool(1), float64(2), int64(3), object(1)
memory usage: 679.4+ KB

In [246]:
 rating = df['rating']
 df.drop(['rating'], axis=1, inplace=True)
 df['rating'] = rating

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12205 entries, 0 to 13392
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         12205 non-null  object
 1   num_subscribers               12205 non-null  int64
 2   num_reviews                   12205 non-null  int64
 3   is_wishlisted                 12205 non-null  bool
 4   num_published_practice_tests  12205 non-null  int64
 5   price_detail__amount          12205 non-null  float64
 6   rating                        12205 non-null  float64
dtypes: bool(1), float64(2), int64(3), object(1)
memory usage: 679.4+ KB

In [248]:
df

,title,num_subscribers,num_reviews,is_wishlisted,num_published_practice_tests,price_detail__amount,rating
0,the complete sql bootcamp 2020 go from zero to...,295509,78006,False,0,8640.0,4.67874
1,tableau 2020 az handson tableau training for d...,209070,54581,False,0,8640.0,4.60015
2,pmp exam prep seminar pmbok guide 6,155282,52653,False,2,8640.0,4.59326
3,the complete financial analyst course 2020,245860,46447,False,0,8640.0,4.53772
4,an entire mba in 1 courseaward winning busines...,374836,41630,False,0,8640.0,4.47173
...,...,...,...,...,...,...,...
13388,cómo hacer staking de criptomonedas,3,0,False,0,3200.0,0.00000
13389,trading semplificato i 5 fattori chiave,4,0,False,0,1280.0,0.00000
13390,geld mit youtube verdienen,2,0,False,0,8640.0,0.00000
13391,trading indices nq,0,0,False,0,2240.0,0.00000
13392,a matemática para investir,1,0,False,0,1280.0,0.00000

In [249]:
from sklearn.preprocessing import LabelEncoder
le_title = LabelEncoder()
le_wishlist = LabelEncoder()
df['title'] = le_title.fit_transform(df['title']) 
df['is_wishlisted'] = le_wishlist.fit_transform(df['is_wishlisted'])

In [250]:
df

,title,num_subscribers,num_reviews,is_wishlisted,num_published_practice_tests,price_detail__amount,rating
0,10856,295509,78006,0,0,8640.0,4.67874
1,10400,209070,54581,0,0,8640.0,4.60015
2,8497,155282,52653,0,2,8640.0,4.59326
3,10768,245860,46447,0,0,8640.0,4.53772
4,804,374836,41630,0,0,8640.0,4.47173
...,...,...,...,...,...,...,...
13388,3065,3,0,0,0,3200.0,0.00000
13389,11341,4,0,0,0,1280.0,0.00000
13390,4704,2,0,0,0,8640.0,0.00000
13391,11313,0,0,0,0,2240.0,0.00000
13392,268,1,0,0,0,1280.0,0.00000

In [251]:
def outliers(df, column):
 Q1 = df[column].quantile(0.25)
 Q3 = df[column].quantile(0.75)
 IQR = Q3- Q1
 outlier_indices = df[(df[column] < (Q1- 1.5 * IQR)) | (df[column] > (Q3 + 1.5 * IQR))].index
 return outlier_indices
outlier_indices = outliers(df, 'num_subscribers')
# conveert to dataframe
outlier_indices = pd.DataFrame(outlier_indices)
outlier_indices

          0
0         0
1         1
2         2
3         3
4         4
...     ...
1441  11857
1442  11877
1443  11889
1444  12039
1445  12131

[1446 rows x 1 columns]

In [252]:
df

,title,num_subscribers,num_reviews,is_wishlisted,num_published_practice_tests,price_detail__amount,rating
0,10856,295509,78006,0,0,8640.0,4.67874
1,10400,209070,54581,0,0,8640.0,4.60015
2,8497,155282,52653,0,2,8640.0,4.59326
3,10768,245860,46447,0,0,8640.0,4.53772
4,804,374836,41630,0,0,8640.0,4.47173
...,...,...,...,...,...,...,...
13388,3065,3,0,0,0,3200.0,0.00000
13389,11341,4,0,0,0,1280.0,0.00000
13390,4704,2,0,0,0,8640.0,0.00000
13391,11313,0,0,0,0,2240.0,0.00000
13392,268,1,0,0,0,1280.0,0.00000

In [253]:
scaler = StandardScaler()
X = df.drop('rating', axis=1) # [1:100] --> [-1:1]
y = df['rating'] 
X

,title,num_subscribers,num_reviews,is_wishlisted,num_published_practice_tests,price_detail__amount
0,10856,295509,78006,0,0,8640.0
1,10400,209070,54581,0,0,8640.0
2,8497,155282,52653,0,2,8640.0
3,10768,245860,46447,0,0,8640.0
4,804,374836,41630,0,0,8640.0
...,...,...,...,...,...,...
13388,3065,3,0,0,0,3200.0
13389,11341,4,0,0,0,1280.0
13390,4704,2,0,0,0,8640.0
13391,11313,0,0,0,0,2240.0
13392,268,1,0,0,0,1280.0

In [254]:
y

0        4.67874
1        4.60015
2        4.59326
3        4.53772
4        4.47173
          ...
13388    0.00000
13389    0.00000
13390    0.00000
13391    0.00000
13392    0.00000
Name: rating, Length: 12205, dtype: float64

In [255]:
numerical_cols = ['num_subscribers', 'num_reviews', 'price_detail__amount']
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

In [256]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

RandomForestRegressor()

In [257]:
train_pred = rf.predict(X_train)
test_pred = rf.predict(X_test)
from sklearn.metrics import mean_squared_error
print('MSE for training data:', (1-mean_squared_error(y_train, train_pred))*100) 
print('MSE for testing data:', (1-mean_squared_error(y_test, test_pred))*100)

MSE for training data: 96.0716053019817
MSE for testing data: 72.61807356156592

In [259]:
import joblib
joblib.dump(le_title, "le_title.pkl")
joblib.dump(le_wishlist, "le_wishlist.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(rf, "rf_model.pkl")

['rf_model.pkl']